services:
  app:
    build:
      ./velospbot
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./velospbot:/velospbot
      - /velospbot/node_modules # 'volume mount'
    command: npm run dev